name: Build Go Project for Windows

on:
  push:
    tags:
      - '*.*.*.*'

jobs:
  build:
    runs-on: windows-latest # 使用最新的 Windows 环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # 检出代码到工作区

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.5' # 指定 Go 版本（根据需要调整）

    - name: Install dependencies
      run: go mod download # 下载依赖

    - name: Build for Windows
      run: go build -o delcmdkey.exe # 编译生成 .exe 文件
      shell: pwsh # 使用 PowerShell 作为 Shell

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: delcmdkey-windows
        path: delcmdkey.exe # 将生成的 .exe 文件上传为构建产物
  
  release:
    needs: build # 等待 build job 完成后执行
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: delcmdkey-windows
        path: . # 将构建产物下载到当前目录

    - name: Show files in directory
      run: ls -R # 显示当前目录下的文件

    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      with:
        files: delcmdkey.exe # 指定要上传到 release 的文件
        draft: false # 发布为正式版本

    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      with:
        files: delcmdkey.exe # 指定要上传到 release 的文件
        draft: false # 发布为正式版本