name: Build Go Project for Windows

on:
  push:
    branches:
      - main # 触发条件：当推送到 main 分支时触发
  pull_request:
    branches:
      - main # 触发条件：当向 main 分支发起 PR 时触发

jobs:
  build:
    runs-on: windows-latest # 使用最新的 Windows 环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 # 检出代码到工作区

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20' # 指定 Go 版本（根据需要调整）

    - name: Install dependencies
      run: go mod download # 下载依赖

    - name: Build for Windows
      run: go build -o delcmdkey.exe . # 编译生成 .exe 文件
      shell: pwsh # 使用 PowerShell 作为 Shell

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: delcmdkey-windows
        path: delcmdkey.exe # 将生成的 .exe 文件上传为构建产物
